version: '3'
services:
  server:
    container_name: server_fastapi
    restart: always
    build:
      context: server
      dockerfile: Backend.Dockerfile
    ports:
      - 8082:8082 # Map port 8082 on the host to port 8082 on the container
    environment:
      - APP_ENV=prod # Set environment variable for production
    volumes:
      - /media:/media # Mount /media from the host to /media in the container
      - /mnt:/mnt # Mount /mnt from the host to /mnt in the container
    networks:
      - homeserver-network

  client:
    container_name: client_react_vite
    restart: always
    build:
      context: client
      dockerfile: Frontend.Dockerfile
    ports:
      - 5173:5173 # Map port 3000 on the host to port 3000 on the container
    # environment:
    #   - NODE_ENV=production # Set environment variable for production
    networks:
      - homeserver-network
    depends_on:
      - server

networks:
  homeserver-network:
    driver: bridge
